# Generated by Django 4.1.5 on 2023-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_email',
            field=models.BooleanField(default=True, verbose_name='Email настоящий'),
            preserve_default=False,
        ),
    ]
