# Generated by Django 4.1.5 on 2023-05-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_alter_profile_options_alter_workers_options_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg_id',
            field=models.BigIntegerField(verbose_name='tg_id'),
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.profile')),
            ],
            options={
                'verbose_name': 'Настроение',
            },
        ),
        migrations.CreateModel(
            name='LastMoodNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reminder_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.profile')),
            ],
            options={
                'verbose_name': 'Последнее настроение',
            },
        ),
    ]
